#!/bin/sh
echo "* Install Please *"
echo "* E2 Restart Is Required *"

if [ -f /usr/share/enigma2/Remove_MetriXconfluencExp ]; then
    echo
    echo "Renaming python modules ... from .pyc to .pyo"
	rm -rf /usr/share/enigma2/Remove_MetriXconfluencExp
	rm -rf /usr/uninstall/Remove_Remove_MetriXconfluencExp.del

exit 0

